###################################
#        Basic Services           #
#        for Development          #
#                                 #
#    Do not use for Production!   #
#                                 #
#       Mediengruppe KLAMBT       #
#            TimWeyand            # 
#                                 #
###################################
version: '2'
services:
  drupal_memcached:
    image: memcached:alpine
    container_name: drupal_memcached
  drupal_solr:
    image: solr:alpine
    container_name: drupal_solr
    ports:
      - "8983:8983"
  drupal_database:
    image: mysql:5.7
    container_name: drupal_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal8
      - MYSQL_USER=drupal8
      - MYSQL_PASSWORD=drupal8
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: drupal_phpmyadmin
    ports:
      - "81:80"    
    links:
      - drupal_database:db     
  webserver:
    image: klambt/drupal:latest
    container_name: webserver_drupal
    links:
      - drupal_memcached
      - drupal_solr
      - drupal_database
  drupal_varnish:
    image: klambt/varnish:latest
    container_name: drupal_varnish   
    links: 
      - webserver:backend-app
    ports:
      - "80:80"
  watchtower:
    image: centurylink/watchtower
    container_name: watchtower
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock