FROM klambt/webserver:latest
MAINTAINER Tim Weyand <tim.weyand@klambt.de>

ENV UPDATE_DEBIAN              1
ENV INSTALL_DRUSH              1
ENV INSTALL_DRUPAL             1

COPY ./scripts/* /usr/local/bin/

RUN chmod +x /usr/local/bin/klambt_docker_*.sh \
 && /usr/local/bin/klambt_docker_update_debian.sh \
 && /usr/local/bin/klambt_docker_install_drush.sh \
 && /usr/local/bin/klambt_docker_install_thunder.sh 
 
# @todo customization
CMD ["/usr/local/bin/klambt_docker_drupal_start.sh"]