###################################
#        Basic Services           #
#        for Development          #
#                                 #
#    Do not use for Production!   #
#                                 #
#       Mediengruppe KLAMBT       #
#            TimWeyand            # 
#                                 #
###################################
version: '2'
services:
  drupal_memcached:
    image: memcached:alpine
    container_name: drupal_memcached
    networks:
      - klambt_drupal
  drupal_database:
    image: mysql:5.7
    container_name: drupal_database
    networks:
      - klambt_drupal
    ports:
      - "3306:3306"
    env_file:
      - ./database.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: drupal_phpmyadmin
    networks:
      - klambt_drupal
    ports:
      - "81:80" 
    depends_on:
      - drupal_database  
  drupal_webserver:
    image: klambt/drupal:latest
    container_name: drupal_webserver
    networks:
      - klambt_drupal
    env_file:
      - ./database.env
      - ./drupal.env
      - ./varnish.env      
    depends_on:
      - drupal_database  
    privileged: true 
  drupal_varnish:
    image: klambt/varnish:latest
    container_name: drupal_varnish   
    networks:
      - klambt_drupal
    env_file:
      - ./varnish.env       
    ports:
      - "80:80"
    expose:
      - "6082"
    depends_on:
      - drupal_webserver 
  drupal_solr:
    image: klambt/solr
    container_name: drupal_solr
    networks:
      - klambt_drupal
    expose:
      - "8983"

networks:
  klambt_drupal:
    driver: bridge